### ISSUE TITLE
The retroarche guide needs fixing.

### ISSUE THREAD

**Issue by audiogamer22** [devinprater/accessible-retro-games#1]
Since I can't post in the forum, (it has some wierd rules) I'll post here.

The retroarche guide needs updating, for one thing you don't press the right arrow to go to settings, you press the left arrow.

Also, I can't understand how you're meant to set up the AI OCR thing with the URL, it's quite unclear.

I'm meant to paste the URL into the settings with my key but I've tried that with the quotes and it doesn't work.

**Comment by devinprater** [comment]
I fixed the guide a bit, adding a way to switch from the now default "ozone" UI to the older, but more simple XMB. The ZTranslate thing was for pasting the code into the Retroarch config file.
